In [16]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

In [17]:
type(list_)

list

In [18]:
type(array_list)

numpy.ndarray

**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [19]:
for i in list_:
  x=type(i)
  print(x)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
for i in array_list:
  x=type(i)
  print(x)

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.**

In [22]:
array_list = np.array(object = list_, dtype = int)

In [24]:
for i in array_list:
  x=type(i)
  print(x)

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Consider the below code to answer further questions:**

In [25]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

**Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size**

In [27]:
num_array.shape

(2, 3)

In [29]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [30]:
num_array.size

6

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]**

In [36]:
m=np.zeros((3,3))

In [37]:
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
m=np.matrix(np.zeros((3,3)))

In [39]:
m

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [40]:
im=np.eye(5)

In [41]:
im

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
m=np.matrix(np.eye(5,dtype=int))

In [46]:
m

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])